interface PDFTemplateProps {
  title: string
  content: string
  subject?: string
  className?: string
}

export default function PDFTemplate({
  title,
  content,
  subject = "Computer Science",
  className = "Class 11",
}: PDFTemplateProps) {
  // Clean HTML content for PDF generation
  const cleanContent = content
    .replace(/<[^>]*>/g, "") // Remove HTML tags
    .replace(/&nbsp;/g, " ") // Replace non-breaking spaces
    .replace(/&amp;/g, "&") // Replace HTML entities
    .replace(/&lt;/g, "<")
    .replace(/&gt;/g, ">")
    .replace(/&quot;/g, '"')
    .replace(/&#39;/g, "'")

  return (
    <div
      style={{
        fontFamily: "Arial, sans-serif",
        padding: "40px",
        lineHeight: "1.6",
        color: "#333",
      }}
    >
      {/* Header */}
      <div
        style={{
          textAlign: "center",
          marginBottom: "40px",
          borderBottom: "2px solid #1f888f",
          paddingBottom: "20px",
        }}
      >
        <div
          style={{
            fontSize: "24px",
            fontWeight: "bold",
            color: "#1f888f",
            marginBottom: "10px",
          }}
        >
          TUTELAGE
        </div>
        <div
          style={{
            fontSize: "14px",
            color: "#666",
            marginBottom: "5px",
          }}
        >
          Educational Excellence Platform
        </div>
        <div
          style={{
            fontSize: "12px",
            color: "#888",
          }}
        >
          {subject} • {className}
        </div>
      </div>

      {/* Title */}
      <h1
        style={{
          fontSize: "28px",
          fontWeight: "bold",
          color: "#2c3e50",
          marginBottom: "30px",
          textAlign: "center",
        }}
      >
        {title}
      </h1>

      {/* Content */}
      <div
        style={{
          fontSize: "14px",
          lineHeight: "1.8",
          textAlign: "justify",
        }}
      >
        {cleanContent.split("\n").map(
          (paragraph, index) =>
            paragraph.trim() && (
              <p
                key={index}
                style={{
                  marginBottom: "15px",
                  textIndent: "20px",
                }}
              >
                {paragraph.trim()}
              </p>
            ),
        )}
      </div>

      {/* Footer */}
      <div
        style={{
          marginTop: "60px",
          paddingTop: "20px",
          borderTop: "1px solid #ddd",
          textAlign: "center",
          fontSize: "12px",
          color: "#666",
        }}
      >
        <div style={{ marginBottom: "5px" }}>Generated by Tutelage Educational Platform</div>
        <div>Visit us at: www.tutelage.com | Contact: info@tutelage.com</div>
        <div style={{ marginTop: "10px", fontSize: "10px", color: "#888" }}>© 2024 Tutelage. All rights reserved.</div>
      </div>
    </div>
  )
}
